// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: media.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializeaudioConfig")
public inline fun audioConfig(block: droidlink.protocol.AudioConfigKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Media.AudioConfig =
  droidlink.protocol.AudioConfigKt.Dsl._create(droidlink.protocol.Media.AudioConfig.newBuilder()).apply { block() }._build()
/**
 * ```
 * Audio configuration
 * ```
 *
 * Protobuf type `droidlink.protocol.AudioConfig`
 */
public object AudioConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.Media.AudioConfig.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.Media.AudioConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.Media.AudioConfig = _builder.build()

    /**
     * ```
     * e.g., 44100, 48000
     * ```
     *
     * `int32 sample_rate = 1;`
     */
    public var sampleRate: kotlin.Int
      @kotlin.jvm.JvmName("getSampleRate")
        get() = _builder.sampleRate
      @kotlin.jvm.JvmName("setSampleRate")
        set(value) {
        _builder.sampleRate = value
      }
    /**
     * ```
     * e.g., 44100, 48000
     * ```
     *
     * `int32 sample_rate = 1;`
     */
    public fun clearSampleRate() {
      _builder.clearSampleRate()
    }

    /**
     * ```
     * 1 = mono, 2 = stereo
     * ```
     *
     * `int32 channels = 2;`
     */
    public var channels: kotlin.Int
      @kotlin.jvm.JvmName("getChannels")
        get() = _builder.channels
      @kotlin.jvm.JvmName("setChannels")
        set(value) {
        _builder.channels = value
      }
    /**
     * ```
     * 1 = mono, 2 = stereo
     * ```
     *
     * `int32 channels = 2;`
     */
    public fun clearChannels() {
      _builder.clearChannels()
    }

    /**
     * `.droidlink.protocol.AudioCodec codec = 3;`
     */
    public var codec: droidlink.protocol.Media.AudioCodec
      @kotlin.jvm.JvmName("getCodec")
        get() = _builder.codec
      @kotlin.jvm.JvmName("setCodec")
        set(value) {
        _builder.codec = value
      }
    public var codecValue: kotlin.Int
      @kotlin.jvm.JvmName("getCodecValue")
        get() = _builder.codecValue
      @kotlin.jvm.JvmName("setCodecValue")
        set(value) {
        _builder.codecValue = value
      }
    /**
     * `.droidlink.protocol.AudioCodec codec = 3;`
     */
    public fun clearCodec() {
      _builder.clearCodec()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.Media.AudioConfig.copy(block: `droidlink.protocol`.AudioConfigKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Media.AudioConfig =
  `droidlink.protocol`.AudioConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

