// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: call.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializecallMessage")
public inline fun callMessage(block: droidlink.protocol.CallMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Call.CallMessage =
  droidlink.protocol.CallMessageKt.Dsl._create(droidlink.protocol.Call.CallMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * Call handling messages
 * ```
 *
 * Protobuf type `droidlink.protocol.CallMessage`
 */
public object CallMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.Call.CallMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.Call.CallMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.Call.CallMessage = _builder.build()

    /**
     * `.droidlink.protocol.CallMessage.CallEventType event = 1;`
     */
    public var event: droidlink.protocol.Call.CallMessage.CallEventType
      @kotlin.jvm.JvmName("getEvent")
        get() = _builder.event
      @kotlin.jvm.JvmName("setEvent")
        set(value) {
        _builder.event = value
      }
    public var eventValue: kotlin.Int
      @kotlin.jvm.JvmName("getEventValue")
        get() = _builder.eventValue
      @kotlin.jvm.JvmName("setEventValue")
        set(value) {
        _builder.eventValue = value
      }
    /**
     * `.droidlink.protocol.CallMessage.CallEventType event = 1;`
     */
    public fun clearEvent() {
      _builder.clearEvent()
    }

    /**
     * ```
     * For RINGING, ANSWERED, MISSED
     * ```
     *
     * `string phone_number = 2;`
     */
    public var phoneNumber: kotlin.String
      @kotlin.jvm.JvmName("getPhoneNumber")
        get() = _builder.phoneNumber
      @kotlin.jvm.JvmName("setPhoneNumber")
        set(value) {
        _builder.phoneNumber = value
      }
    /**
     * ```
     * For RINGING, ANSWERED, MISSED
     * ```
     *
     * `string phone_number = 2;`
     */
    public fun clearPhoneNumber() {
      _builder.clearPhoneNumber()
    }

    /**
     * `string contact_name = 3;`
     */
    public var contactName: kotlin.String
      @kotlin.jvm.JvmName("getContactName")
        get() = _builder.contactName
      @kotlin.jvm.JvmName("setContactName")
        set(value) {
        _builder.contactName = value
      }
    /**
     * `string contact_name = 3;`
     */
    public fun clearContactName() {
      _builder.clearContactName()
    }

    /**
     * ```
     * Contact photo (PNG)
     * ```
     *
     * `bytes contact_photo = 4;`
     */
    public var contactPhoto: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getContactPhoto")
        get() = _builder.contactPhoto
      @kotlin.jvm.JvmName("setContactPhoto")
        set(value) {
        _builder.contactPhoto = value
      }
    /**
     * ```
     * Contact photo (PNG)
     * ```
     *
     * `bytes contact_photo = 4;`
     */
    public fun clearContactPhoto() {
      _builder.clearContactPhoto()
    }

    /**
     * `int64 timestamp = 5;`
     */
    public var timestamp: kotlin.Long
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `int64 timestamp = 5;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }

    /**
     * ```
     * Unique call ID
     * ```
     *
     * `string call_id = 6;`
     */
    public var callId: kotlin.String
      @kotlin.jvm.JvmName("getCallId")
        get() = _builder.callId
      @kotlin.jvm.JvmName("setCallId")
        set(value) {
        _builder.callId = value
      }
    /**
     * ```
     * Unique call ID
     * ```
     *
     * `string call_id = 6;`
     */
    public fun clearCallId() {
      _builder.clearCallId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.Call.CallMessage.copy(block: `droidlink.protocol`.CallMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Call.CallMessage =
  `droidlink.protocol`.CallMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

