// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: call.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializecallAction")
public inline fun callAction(block: droidlink.protocol.CallActionKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Call.CallAction =
  droidlink.protocol.CallActionKt.Dsl._create(droidlink.protocol.Call.CallAction.newBuilder()).apply { block() }._build()
/**
 * ```
 * Call action from Mac to Android
 * ```
 *
 * Protobuf type `droidlink.protocol.CallAction`
 */
public object CallActionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.Call.CallAction.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.Call.CallAction.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.Call.CallAction = _builder.build()

    /**
     * `.droidlink.protocol.CallAction.ActionType action = 1;`
     */
    public var action: droidlink.protocol.Call.CallAction.ActionType
      @kotlin.jvm.JvmName("getAction")
        get() = _builder.action
      @kotlin.jvm.JvmName("setAction")
        set(value) {
        _builder.action = value
      }
    public var actionValue: kotlin.Int
      @kotlin.jvm.JvmName("getActionValue")
        get() = _builder.actionValue
      @kotlin.jvm.JvmName("setActionValue")
        set(value) {
        _builder.actionValue = value
      }
    /**
     * `.droidlink.protocol.CallAction.ActionType action = 1;`
     */
    public fun clearAction() {
      _builder.clearAction()
    }

    /**
     * `string call_id = 2;`
     */
    public var callId: kotlin.String
      @kotlin.jvm.JvmName("getCallId")
        get() = _builder.callId
      @kotlin.jvm.JvmName("setCallId")
        set(value) {
        _builder.callId = value
      }
    /**
     * `string call_id = 2;`
     */
    public fun clearCallId() {
      _builder.clearCallId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.Call.CallAction.copy(block: `droidlink.protocol`.CallActionKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Call.CallAction =
  `droidlink.protocol`.CallActionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

