// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: media.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializecameraConfig")
public inline fun cameraConfig(block: droidlink.protocol.CameraConfigKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Media.CameraConfig =
  droidlink.protocol.CameraConfigKt.Dsl._create(droidlink.protocol.Media.CameraConfig.newBuilder()).apply { block() }._build()
/**
 * ```
 * Camera configuration
 * ```
 *
 * Protobuf type `droidlink.protocol.CameraConfig`
 */
public object CameraConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.Media.CameraConfig.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.Media.CameraConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.Media.CameraConfig = _builder.build()

    /**
     * `int32 width = 1;`
     */
    public var width: kotlin.Int
      @kotlin.jvm.JvmName("getWidth")
        get() = _builder.width
      @kotlin.jvm.JvmName("setWidth")
        set(value) {
        _builder.width = value
      }
    /**
     * `int32 width = 1;`
     */
    public fun clearWidth() {
      _builder.clearWidth()
    }

    /**
     * `int32 height = 2;`
     */
    public var height: kotlin.Int
      @kotlin.jvm.JvmName("getHeight")
        get() = _builder.height
      @kotlin.jvm.JvmName("setHeight")
        set(value) {
        _builder.height = value
      }
    /**
     * `int32 height = 2;`
     */
    public fun clearHeight() {
      _builder.clearHeight()
    }

    /**
     * `int32 fps = 3;`
     */
    public var fps: kotlin.Int
      @kotlin.jvm.JvmName("getFps")
        get() = _builder.fps
      @kotlin.jvm.JvmName("setFps")
        set(value) {
        _builder.fps = value
      }
    /**
     * `int32 fps = 3;`
     */
    public fun clearFps() {
      _builder.clearFps()
    }

    /**
     * `.droidlink.protocol.CameraFacing facing = 4;`
     */
    public var facing: droidlink.protocol.Media.CameraFacing
      @kotlin.jvm.JvmName("getFacing")
        get() = _builder.facing
      @kotlin.jvm.JvmName("setFacing")
        set(value) {
        _builder.facing = value
      }
    public var facingValue: kotlin.Int
      @kotlin.jvm.JvmName("getFacingValue")
        get() = _builder.facingValue
      @kotlin.jvm.JvmName("setFacingValue")
        set(value) {
        _builder.facingValue = value
      }
    /**
     * `.droidlink.protocol.CameraFacing facing = 4;`
     */
    public fun clearFacing() {
      _builder.clearFacing()
    }

    /**
     * `.droidlink.protocol.VideoCodec codec = 5;`
     */
    public var codec: droidlink.protocol.Screen.VideoCodec
      @kotlin.jvm.JvmName("getCodec")
        get() = _builder.codec
      @kotlin.jvm.JvmName("setCodec")
        set(value) {
        _builder.codec = value
      }
    public var codecValue: kotlin.Int
      @kotlin.jvm.JvmName("getCodecValue")
        get() = _builder.codecValue
      @kotlin.jvm.JvmName("setCodecValue")
        set(value) {
        _builder.codecValue = value
      }
    /**
     * `.droidlink.protocol.VideoCodec codec = 5;`
     */
    public fun clearCodec() {
      _builder.clearCodec()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.Media.CameraConfig.copy(block: `droidlink.protocol`.CameraConfigKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Media.CameraConfig =
  `droidlink.protocol`.CameraConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

