// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: clipboard.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializeclipboardData")
public inline fun clipboardData(block: droidlink.protocol.ClipboardDataKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Clipboard.ClipboardData =
  droidlink.protocol.ClipboardDataKt.Dsl._create(droidlink.protocol.Clipboard.ClipboardData.newBuilder()).apply { block() }._build()
/**
 * ```
 * Clipboard data (text, image, URL)
 * ```
 *
 * Protobuf type `droidlink.protocol.ClipboardData`
 */
public object ClipboardDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.Clipboard.ClipboardData.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.Clipboard.ClipboardData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.Clipboard.ClipboardData = _builder.build()

    /**
     * `.droidlink.protocol.DataType type = 1;`
     */
    public var type: droidlink.protocol.Clipboard.DataType
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    public var typeValue: kotlin.Int
      @kotlin.jvm.JvmName("getTypeValue")
        get() = _builder.typeValue
      @kotlin.jvm.JvmName("setTypeValue")
        set(value) {
        _builder.typeValue = value
      }
    /**
     * `.droidlink.protocol.DataType type = 1;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `string text = 2;`
     */
    public var text: kotlin.String
      @kotlin.jvm.JvmName("getText")
        get() = _builder.text
      @kotlin.jvm.JvmName("setText")
        set(value) {
        _builder.text = value
      }
    /**
     * `string text = 2;`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * ```
     * PNG or JPEG
     * ```
     *
     * `bytes image_data = 3;`
     */
    public var imageData: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getImageData")
        get() = _builder.imageData
      @kotlin.jvm.JvmName("setImageData")
        set(value) {
        _builder.imageData = value
      }
    /**
     * ```
     * PNG or JPEG
     * ```
     *
     * `bytes image_data = 3;`
     */
    public fun clearImageData() {
      _builder.clearImageData()
    }

    /**
     * `string url = 4;`
     */
    public var url: kotlin.String
      @kotlin.jvm.JvmName("getUrl")
        get() = _builder.url
      @kotlin.jvm.JvmName("setUrl")
        set(value) {
        _builder.url = value
      }
    /**
     * `string url = 4;`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }

    /**
     * ```
     * When copied
     * ```
     *
     * `int64 timestamp = 5;`
     */
    public var timestamp: kotlin.Long
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * ```
     * When copied
     * ```
     *
     * `int64 timestamp = 5;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.Clipboard.ClipboardData.copy(block: `droidlink.protocol`.ClipboardDataKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Clipboard.ClipboardData =
  `droidlink.protocol`.ClipboardDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

