// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: clipboard.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializeclipboardMessage")
public inline fun clipboardMessage(block: droidlink.protocol.ClipboardMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Clipboard.ClipboardMessage =
  droidlink.protocol.ClipboardMessageKt.Dsl._create(droidlink.protocol.Clipboard.ClipboardMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * Clipboard synchronization messages
 * ```
 *
 * Protobuf type `droidlink.protocol.ClipboardMessage`
 */
public object ClipboardMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.Clipboard.ClipboardMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.Clipboard.ClipboardMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.Clipboard.ClipboardMessage = _builder.build()

    /**
     * `.droidlink.protocol.ClipboardData data = 1;`
     */
    public var data: droidlink.protocol.Clipboard.ClipboardData
      @kotlin.jvm.JvmName("getData")
        get() = _builder.data
      @kotlin.jvm.JvmName("setData")
        set(value) {
        _builder.data = value
      }
    /**
     * `.droidlink.protocol.ClipboardData data = 1;`
     */
    public fun clearData() {
      _builder.clearData()
    }
    /**
     * `.droidlink.protocol.ClipboardData data = 1;`
     * @return Whether the data field is set.
     */
    public fun hasData(): kotlin.Boolean {
      return _builder.hasData()
    }

    public val ClipboardMessageKt.Dsl.dataOrNull: droidlink.protocol.Clipboard.ClipboardData?
      get() = _builder.dataOrNull

    /**
     * `string source_device_id = 2;`
     */
    public var sourceDeviceId: kotlin.String
      @kotlin.jvm.JvmName("getSourceDeviceId")
        get() = _builder.sourceDeviceId
      @kotlin.jvm.JvmName("setSourceDeviceId")
        set(value) {
        _builder.sourceDeviceId = value
      }
    /**
     * `string source_device_id = 2;`
     */
    public fun clearSourceDeviceId() {
      _builder.clearSourceDeviceId()
    }

    /**
     * ```
     * True if from other device
     * ```
     *
     * `bool is_remote = 3;`
     */
    public var isRemote: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsRemote")
        get() = _builder.isRemote
      @kotlin.jvm.JvmName("setIsRemote")
        set(value) {
        _builder.isRemote = value
      }
    /**
     * ```
     * True if from other device
     * ```
     *
     * `bool is_remote = 3;`
     */
    public fun clearIsRemote() {
      _builder.clearIsRemote()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.Clipboard.ClipboardMessage.copy(block: `droidlink.protocol`.ClipboardMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Clipboard.ClipboardMessage =
  `droidlink.protocol`.ClipboardMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val droidlink.protocol.Clipboard.ClipboardMessageOrBuilder.dataOrNull: droidlink.protocol.Clipboard.ClipboardData?
  get() = if (hasData()) getData() else null

