// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: droidlink.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializedroidLinkMessage")
public inline fun droidLinkMessage(block: droidlink.protocol.DroidLinkMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Droidlink.DroidLinkMessage =
  droidlink.protocol.DroidLinkMessageKt.Dsl._create(droidlink.protocol.Droidlink.DroidLinkMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * Root message type for all DroidLink communication
 * ```
 *
 * Protobuf type `droidlink.protocol.DroidLinkMessage`
 */
public object DroidLinkMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.Droidlink.DroidLinkMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.Droidlink.DroidLinkMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.Droidlink.DroidLinkMessage = _builder.build()

    /**
     * ```
     * Unique message ID (timestamp-based)
     * ```
     *
     * `uint64 id = 1;`
     */
    public var id: kotlin.Long
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * ```
     * Unique message ID (timestamp-based)
     * ```
     *
     * `uint64 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * Unix timestamp (milliseconds)
     * ```
     *
     * `uint64 timestamp = 2;`
     */
    public var timestamp: kotlin.Long
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * ```
     * Unix timestamp (milliseconds)
     * ```
     *
     * `uint64 timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }

    /**
     * ```
     * Message type
     * ```
     *
     * `.droidlink.protocol.MessageType type = 3;`
     */
    public var type: droidlink.protocol.Droidlink.MessageType
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    public var typeValue: kotlin.Int
      @kotlin.jvm.JvmName("getTypeValue")
        get() = _builder.typeValue
      @kotlin.jvm.JvmName("setTypeValue")
        set(value) {
        _builder.typeValue = value
      }
    /**
     * ```
     * Message type
     * ```
     *
     * `.droidlink.protocol.MessageType type = 3;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `.droidlink.protocol.ClipboardMessage clipboard = 10;`
     */
    public var clipboard: droidlink.protocol.Clipboard.ClipboardMessage
      @kotlin.jvm.JvmName("getClipboard")
        get() = _builder.clipboard
      @kotlin.jvm.JvmName("setClipboard")
        set(value) {
        _builder.clipboard = value
      }
    /**
     * `.droidlink.protocol.ClipboardMessage clipboard = 10;`
     */
    public fun clearClipboard() {
      _builder.clearClipboard()
    }
    /**
     * `.droidlink.protocol.ClipboardMessage clipboard = 10;`
     * @return Whether the clipboard field is set.
     */
    public fun hasClipboard(): kotlin.Boolean {
      return _builder.hasClipboard()
    }

    /**
     * `.droidlink.protocol.NotificationMessage notification = 11;`
     */
    public var notification: droidlink.protocol.Notification.NotificationMessage
      @kotlin.jvm.JvmName("getNotification")
        get() = _builder.notification
      @kotlin.jvm.JvmName("setNotification")
        set(value) {
        _builder.notification = value
      }
    /**
     * `.droidlink.protocol.NotificationMessage notification = 11;`
     */
    public fun clearNotification() {
      _builder.clearNotification()
    }
    /**
     * `.droidlink.protocol.NotificationMessage notification = 11;`
     * @return Whether the notification field is set.
     */
    public fun hasNotification(): kotlin.Boolean {
      return _builder.hasNotification()
    }

    /**
     * `.droidlink.protocol.FileMessage file = 12;`
     */
    public var file: droidlink.protocol.File.FileMessage
      @kotlin.jvm.JvmName("getFile")
        get() = _builder.file
      @kotlin.jvm.JvmName("setFile")
        set(value) {
        _builder.file = value
      }
    /**
     * `.droidlink.protocol.FileMessage file = 12;`
     */
    public fun clearFile() {
      _builder.clearFile()
    }
    /**
     * `.droidlink.protocol.FileMessage file = 12;`
     * @return Whether the file field is set.
     */
    public fun hasFile(): kotlin.Boolean {
      return _builder.hasFile()
    }

    /**
     * `.droidlink.protocol.ScreenMessage screen = 13;`
     */
    public var screen: droidlink.protocol.Screen.ScreenMessage
      @kotlin.jvm.JvmName("getScreen")
        get() = _builder.screen
      @kotlin.jvm.JvmName("setScreen")
        set(value) {
        _builder.screen = value
      }
    /**
     * `.droidlink.protocol.ScreenMessage screen = 13;`
     */
    public fun clearScreen() {
      _builder.clearScreen()
    }
    /**
     * `.droidlink.protocol.ScreenMessage screen = 13;`
     * @return Whether the screen field is set.
     */
    public fun hasScreen(): kotlin.Boolean {
      return _builder.hasScreen()
    }

    /**
     * `.droidlink.protocol.MediaMessage media = 14;`
     */
    public var media: droidlink.protocol.Media.MediaMessage
      @kotlin.jvm.JvmName("getMedia")
        get() = _builder.media
      @kotlin.jvm.JvmName("setMedia")
        set(value) {
        _builder.media = value
      }
    /**
     * `.droidlink.protocol.MediaMessage media = 14;`
     */
    public fun clearMedia() {
      _builder.clearMedia()
    }
    /**
     * `.droidlink.protocol.MediaMessage media = 14;`
     * @return Whether the media field is set.
     */
    public fun hasMedia(): kotlin.Boolean {
      return _builder.hasMedia()
    }

    /**
     * `.droidlink.protocol.CallMessage call = 15;`
     */
    public var call: droidlink.protocol.Call.CallMessage
      @kotlin.jvm.JvmName("getCall")
        get() = _builder.call
      @kotlin.jvm.JvmName("setCall")
        set(value) {
        _builder.call = value
      }
    /**
     * `.droidlink.protocol.CallMessage call = 15;`
     */
    public fun clearCall() {
      _builder.clearCall()
    }
    /**
     * `.droidlink.protocol.CallMessage call = 15;`
     * @return Whether the call field is set.
     */
    public fun hasCall(): kotlin.Boolean {
      return _builder.hasCall()
    }

    /**
     * `.droidlink.protocol.SystemMessage system = 16;`
     */
    public var system: droidlink.protocol.System.SystemMessage
      @kotlin.jvm.JvmName("getSystem")
        get() = _builder.system
      @kotlin.jvm.JvmName("setSystem")
        set(value) {
        _builder.system = value
      }
    /**
     * `.droidlink.protocol.SystemMessage system = 16;`
     */
    public fun clearSystem() {
      _builder.clearSystem()
    }
    /**
     * `.droidlink.protocol.SystemMessage system = 16;`
     * @return Whether the system field is set.
     */
    public fun hasSystem(): kotlin.Boolean {
      return _builder.hasSystem()
    }
    public val payloadCase: droidlink.protocol.Droidlink.DroidLinkMessage.PayloadCase
    @kotlin.jvm.JvmName("getPayloadCase")
      get() = _builder.getPayloadCase()

    public fun clearPayload() {
      _builder.clearPayload()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.Droidlink.DroidLinkMessage.copy(block: `droidlink.protocol`.DroidLinkMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Droidlink.DroidLinkMessage =
  `droidlink.protocol`.DroidLinkMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val droidlink.protocol.Droidlink.DroidLinkMessageOrBuilder.clipboardOrNull: droidlink.protocol.Clipboard.ClipboardMessage?
  get() = if (hasClipboard()) getClipboard() else null

public val droidlink.protocol.Droidlink.DroidLinkMessageOrBuilder.notificationOrNull: droidlink.protocol.Notification.NotificationMessage?
  get() = if (hasNotification()) getNotification() else null

public val droidlink.protocol.Droidlink.DroidLinkMessageOrBuilder.fileOrNull: droidlink.protocol.File.FileMessage?
  get() = if (hasFile()) getFile() else null

public val droidlink.protocol.Droidlink.DroidLinkMessageOrBuilder.screenOrNull: droidlink.protocol.Screen.ScreenMessage?
  get() = if (hasScreen()) getScreen() else null

public val droidlink.protocol.Droidlink.DroidLinkMessageOrBuilder.mediaOrNull: droidlink.protocol.Media.MediaMessage?
  get() = if (hasMedia()) getMedia() else null

public val droidlink.protocol.Droidlink.DroidLinkMessageOrBuilder.callOrNull: droidlink.protocol.Call.CallMessage?
  get() = if (hasCall()) getCall() else null

public val droidlink.protocol.Droidlink.DroidLinkMessageOrBuilder.systemOrNull: droidlink.protocol.System.SystemMessage?
  get() = if (hasSystem()) getSystem() else null

