// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: system.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializeerrorMessage")
public inline fun errorMessage(block: droidlink.protocol.ErrorMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.System.ErrorMessage =
  droidlink.protocol.ErrorMessageKt.Dsl._create(droidlink.protocol.System.ErrorMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * Error notification
 * ```
 *
 * Protobuf type `droidlink.protocol.ErrorMessage`
 */
public object ErrorMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.System.ErrorMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.System.ErrorMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.System.ErrorMessage = _builder.build()

    /**
     * `.droidlink.protocol.ErrorCode code = 1;`
     */
    public var code: droidlink.protocol.System.ErrorCode
      @kotlin.jvm.JvmName("getCode")
        get() = _builder.code
      @kotlin.jvm.JvmName("setCode")
        set(value) {
        _builder.code = value
      }
    public var codeValue: kotlin.Int
      @kotlin.jvm.JvmName("getCodeValue")
        get() = _builder.codeValue
      @kotlin.jvm.JvmName("setCodeValue")
        set(value) {
        _builder.codeValue = value
      }
    /**
     * `.droidlink.protocol.ErrorCode code = 1;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * `string message = 2;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * `string details = 3;`
     */
    public var details: kotlin.String
      @kotlin.jvm.JvmName("getDetails")
        get() = _builder.details
      @kotlin.jvm.JvmName("setDetails")
        set(value) {
        _builder.details = value
      }
    /**
     * `string details = 3;`
     */
    public fun clearDetails() {
      _builder.clearDetails()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.System.ErrorMessage.copy(block: `droidlink.protocol`.ErrorMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.System.ErrorMessage =
  `droidlink.protocol`.ErrorMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

