// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: file.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializefileMessage")
public inline fun fileMessage(block: droidlink.protocol.FileMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.File.FileMessage =
  droidlink.protocol.FileMessageKt.Dsl._create(droidlink.protocol.File.FileMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * File transfer messages
 * ```
 *
 * Protobuf type `droidlink.protocol.FileMessage`
 */
public object FileMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.File.FileMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.File.FileMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.File.FileMessage = _builder.build()

    /**
     * `.droidlink.protocol.FileMessage.FileOperation operation = 1;`
     */
    public var operation: droidlink.protocol.File.FileMessage.FileOperation
      @kotlin.jvm.JvmName("getOperation")
        get() = _builder.operation
      @kotlin.jvm.JvmName("setOperation")
        set(value) {
        _builder.operation = value
      }
    public var operationValue: kotlin.Int
      @kotlin.jvm.JvmName("getOperationValue")
        get() = _builder.operationValue
      @kotlin.jvm.JvmName("setOperationValue")
        set(value) {
        _builder.operationValue = value
      }
    /**
     * `.droidlink.protocol.FileMessage.FileOperation operation = 1;`
     */
    public fun clearOperation() {
      _builder.clearOperation()
    }

    /**
     * ```
     * For LIST_REQUEST, DOWNLOAD_REQUEST
     * ```
     *
     * `string file_path = 2;`
     */
    public var filePath: kotlin.String
      @kotlin.jvm.JvmName("getFilePath")
        get() = _builder.filePath
      @kotlin.jvm.JvmName("setFilePath")
        set(value) {
        _builder.filePath = value
      }
    /**
     * ```
     * For LIST_REQUEST, DOWNLOAD_REQUEST
     * ```
     *
     * `string file_path = 2;`
     */
    public fun clearFilePath() {
      _builder.clearFilePath()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class FilesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * For LIST_RESPONSE
     * ```
     *
     * `repeated .droidlink.protocol.FileInfo files = 3;`
     */
     public val files: com.google.protobuf.kotlin.DslList<droidlink.protocol.File.FileInfo, FilesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.filesList
      )
    /**
     * ```
     * For LIST_RESPONSE
     * ```
     *
     * `repeated .droidlink.protocol.FileInfo files = 3;`
     * @param value The files to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addFiles")
    public fun com.google.protobuf.kotlin.DslList<droidlink.protocol.File.FileInfo, FilesProxy>.add(value: droidlink.protocol.File.FileInfo) {
      _builder.addFiles(value)
    }
    /**
     * ```
     * For LIST_RESPONSE
     * ```
     *
     * `repeated .droidlink.protocol.FileInfo files = 3;`
     * @param value The files to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignFiles")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<droidlink.protocol.File.FileInfo, FilesProxy>.plusAssign(value: droidlink.protocol.File.FileInfo) {
      add(value)
    }
    /**
     * ```
     * For LIST_RESPONSE
     * ```
     *
     * `repeated .droidlink.protocol.FileInfo files = 3;`
     * @param values The files to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllFiles")
    public fun com.google.protobuf.kotlin.DslList<droidlink.protocol.File.FileInfo, FilesProxy>.addAll(values: kotlin.collections.Iterable<droidlink.protocol.File.FileInfo>) {
      _builder.addAllFiles(values)
    }
    /**
     * ```
     * For LIST_RESPONSE
     * ```
     *
     * `repeated .droidlink.protocol.FileInfo files = 3;`
     * @param values The files to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllFiles")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<droidlink.protocol.File.FileInfo, FilesProxy>.plusAssign(values: kotlin.collections.Iterable<droidlink.protocol.File.FileInfo>) {
      addAll(values)
    }
    /**
     * ```
     * For LIST_RESPONSE
     * ```
     *
     * `repeated .droidlink.protocol.FileInfo files = 3;`
     * @param index The index to set the value at.
     * @param value The files to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setFiles")
    public operator fun com.google.protobuf.kotlin.DslList<droidlink.protocol.File.FileInfo, FilesProxy>.set(index: kotlin.Int, value: droidlink.protocol.File.FileInfo) {
      _builder.setFiles(index, value)
    }
    /**
     * ```
     * For LIST_RESPONSE
     * ```
     *
     * `repeated .droidlink.protocol.FileInfo files = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearFiles")
    public fun com.google.protobuf.kotlin.DslList<droidlink.protocol.File.FileInfo, FilesProxy>.clear() {
      _builder.clearFiles()
    }

    /**
     * ```
     * For DOWNLOAD_REQUEST, DOWNLOAD_RESPONSE
     * ```
     *
     * `int64 file_size = 4;`
     */
    public var fileSize: kotlin.Long
      @kotlin.jvm.JvmName("getFileSize")
        get() = _builder.fileSize
      @kotlin.jvm.JvmName("setFileSize")
        set(value) {
        _builder.fileSize = value
      }
    /**
     * ```
     * For DOWNLOAD_REQUEST, DOWNLOAD_RESPONSE
     * ```
     *
     * `int64 file_size = 4;`
     */
    public fun clearFileSize() {
      _builder.clearFileSize()
    }

    /**
     * `string mime_type = 5;`
     */
    public var mimeType: kotlin.String
      @kotlin.jvm.JvmName("getMimeType")
        get() = _builder.mimeType
      @kotlin.jvm.JvmName("setMimeType")
        set(value) {
        _builder.mimeType = value
      }
    /**
     * `string mime_type = 5;`
     */
    public fun clearMimeType() {
      _builder.clearMimeType()
    }

    /**
     * ```
     * Chunked data
     * ```
     *
     * `bytes file_data = 6;`
     */
    public var fileData: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getFileData")
        get() = _builder.fileData
      @kotlin.jvm.JvmName("setFileData")
        set(value) {
        _builder.fileData = value
      }
    /**
     * ```
     * Chunked data
     * ```
     *
     * `bytes file_data = 6;`
     */
    public fun clearFileData() {
      _builder.clearFileData()
    }

    /**
     * ```
     * Chunk number (0-based)
     * ```
     *
     * `int32 chunk_index = 7;`
     */
    public var chunkIndex: kotlin.Int
      @kotlin.jvm.JvmName("getChunkIndex")
        get() = _builder.chunkIndex
      @kotlin.jvm.JvmName("setChunkIndex")
        set(value) {
        _builder.chunkIndex = value
      }
    /**
     * ```
     * Chunk number (0-based)
     * ```
     *
     * `int32 chunk_index = 7;`
     */
    public fun clearChunkIndex() {
      _builder.clearChunkIndex()
    }

    /**
     * ```
     * Total chunks
     * ```
     *
     * `int32 total_chunks = 8;`
     */
    public var totalChunks: kotlin.Int
      @kotlin.jvm.JvmName("getTotalChunks")
        get() = _builder.totalChunks
      @kotlin.jvm.JvmName("setTotalChunks")
        set(value) {
        _builder.totalChunks = value
      }
    /**
     * ```
     * Total chunks
     * ```
     *
     * `int32 total_chunks = 8;`
     */
    public fun clearTotalChunks() {
      _builder.clearTotalChunks()
    }

    /**
     * ```
     * Unique transfer ID
     * ```
     *
     * `string file_id = 9;`
     */
    public var fileId: kotlin.String
      @kotlin.jvm.JvmName("getFileId")
        get() = _builder.fileId
      @kotlin.jvm.JvmName("setFileId")
        set(value) {
        _builder.fileId = value
      }
    /**
     * ```
     * Unique transfer ID
     * ```
     *
     * `string file_id = 9;`
     */
    public fun clearFileId() {
      _builder.clearFileId()
    }

    /**
     * ```
     * For ERROR
     * ```
     *
     * `string error_message = 10;`
     */
    public var errorMessage: kotlin.String
      @kotlin.jvm.JvmName("getErrorMessage")
        get() = _builder.errorMessage
      @kotlin.jvm.JvmName("setErrorMessage")
        set(value) {
        _builder.errorMessage = value
      }
    /**
     * ```
     * For ERROR
     * ```
     *
     * `string error_message = 10;`
     */
    public fun clearErrorMessage() {
      _builder.clearErrorMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.File.FileMessage.copy(block: `droidlink.protocol`.FileMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.File.FileMessage =
  `droidlink.protocol`.FileMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

