// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: file.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializefileInfo")
public inline fun fileInfo(block: droidlink.protocol.FileInfoKt.Dsl.() -> kotlin.Unit): droidlink.protocol.File.FileInfo =
  droidlink.protocol.FileInfoKt.Dsl._create(droidlink.protocol.File.FileInfo.newBuilder()).apply { block() }._build()
/**
 * ```
 * File information
 * ```
 *
 * Protobuf type `droidlink.protocol.FileInfo`
 */
public object FileInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.File.FileInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.File.FileInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.File.FileInfo = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string path = 2;`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 2;`
     */
    public fun clearPath() {
      _builder.clearPath()
    }

    /**
     * `int64 size = 3;`
     */
    public var size: kotlin.Long
      @kotlin.jvm.JvmName("getSize")
        get() = _builder.size
      @kotlin.jvm.JvmName("setSize")
        set(value) {
        _builder.size = value
      }
    /**
     * `int64 size = 3;`
     */
    public fun clearSize() {
      _builder.clearSize()
    }

    /**
     * `int64 modified_time = 4;`
     */
    public var modifiedTime: kotlin.Long
      @kotlin.jvm.JvmName("getModifiedTime")
        get() = _builder.modifiedTime
      @kotlin.jvm.JvmName("setModifiedTime")
        set(value) {
        _builder.modifiedTime = value
      }
    /**
     * `int64 modified_time = 4;`
     */
    public fun clearModifiedTime() {
      _builder.clearModifiedTime()
    }

    /**
     * `bool is_directory = 5;`
     */
    public var isDirectory: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsDirectory")
        get() = _builder.isDirectory
      @kotlin.jvm.JvmName("setIsDirectory")
        set(value) {
        _builder.isDirectory = value
      }
    /**
     * `bool is_directory = 5;`
     */
    public fun clearIsDirectory() {
      _builder.clearIsDirectory()
    }

    /**
     * `string mime_type = 6;`
     */
    public var mimeType: kotlin.String
      @kotlin.jvm.JvmName("getMimeType")
        get() = _builder.mimeType
      @kotlin.jvm.JvmName("setMimeType")
        set(value) {
        _builder.mimeType = value
      }
    /**
     * `string mime_type = 6;`
     */
    public fun clearMimeType() {
      _builder.clearMimeType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.File.FileInfo.copy(block: `droidlink.protocol`.FileInfoKt.Dsl.() -> kotlin.Unit): droidlink.protocol.File.FileInfo =
  `droidlink.protocol`.FileInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

