// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: system.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializehelloMessage")
public inline fun helloMessage(block: droidlink.protocol.HelloMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.System.HelloMessage =
  droidlink.protocol.HelloMessageKt.Dsl._create(droidlink.protocol.System.HelloMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * Initial handshake message from client
 * ```
 *
 * Protobuf type `droidlink.protocol.HelloMessage`
 */
public object HelloMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.System.HelloMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.System.HelloMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.System.HelloMessage = _builder.build()

    /**
     * ```
     * e.g., "1.0.0"
     * ```
     *
     * `string protocol_version = 1;`
     */
    public var protocolVersion: kotlin.String
      @kotlin.jvm.JvmName("getProtocolVersion")
        get() = _builder.protocolVersion
      @kotlin.jvm.JvmName("setProtocolVersion")
        set(value) {
        _builder.protocolVersion = value
      }
    /**
     * ```
     * e.g., "1.0.0"
     * ```
     *
     * `string protocol_version = 1;`
     */
    public fun clearProtocolVersion() {
      _builder.clearProtocolVersion()
    }

    /**
     * ```
     * Unique device ID
     * ```
     *
     * `string device_id = 2;`
     */
    public var deviceId: kotlin.String
      @kotlin.jvm.JvmName("getDeviceId")
        get() = _builder.deviceId
      @kotlin.jvm.JvmName("setDeviceId")
        set(value) {
        _builder.deviceId = value
      }
    /**
     * ```
     * Unique device ID
     * ```
     *
     * `string device_id = 2;`
     */
    public fun clearDeviceId() {
      _builder.clearDeviceId()
    }

    /**
     * ```
     * User-friendly name
     * ```
     *
     * `string device_name = 3;`
     */
    public var deviceName: kotlin.String
      @kotlin.jvm.JvmName("getDeviceName")
        get() = _builder.deviceName
      @kotlin.jvm.JvmName("setDeviceName")
        set(value) {
        _builder.deviceName = value
      }
    /**
     * ```
     * User-friendly name
     * ```
     *
     * `string device_name = 3;`
     */
    public fun clearDeviceName() {
      _builder.clearDeviceName()
    }

    /**
     * ```
     * Android or Mac/iPad
     * ```
     *
     * `.droidlink.protocol.DeviceType device_type = 4;`
     */
    public var deviceType: droidlink.protocol.System.DeviceType
      @kotlin.jvm.JvmName("getDeviceType")
        get() = _builder.deviceType
      @kotlin.jvm.JvmName("setDeviceType")
        set(value) {
        _builder.deviceType = value
      }
    public var deviceTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getDeviceTypeValue")
        get() = _builder.deviceTypeValue
      @kotlin.jvm.JvmName("setDeviceTypeValue")
        set(value) {
        _builder.deviceTypeValue = value
      }
    /**
     * ```
     * Android or Mac/iPad
     * ```
     *
     * `.droidlink.protocol.DeviceType device_type = 4;`
     */
    public fun clearDeviceType() {
      _builder.clearDeviceType()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SupportedFeaturesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Feature list
     * ```
     *
     * `repeated string supported_features = 5;`
     * @return A list containing the supportedFeatures.
     */
    public val supportedFeatures: com.google.protobuf.kotlin.DslList<kotlin.String, SupportedFeaturesProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.supportedFeaturesList
      )
    /**
     * ```
     * Feature list
     * ```
     *
     * `repeated string supported_features = 5;`
     * @param value The supportedFeatures to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addSupportedFeatures")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, SupportedFeaturesProxy>.add(value: kotlin.String) {
      _builder.addSupportedFeatures(value)
    }
    /**
     * ```
     * Feature list
     * ```
     *
     * `repeated string supported_features = 5;`
     * @param value The supportedFeatures to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignSupportedFeatures")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SupportedFeaturesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * Feature list
     * ```
     *
     * `repeated string supported_features = 5;`
     * @param values The supportedFeatures to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllSupportedFeatures")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, SupportedFeaturesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllSupportedFeatures(values)
    }
    /**
     * ```
     * Feature list
     * ```
     *
     * `repeated string supported_features = 5;`
     * @param values The supportedFeatures to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllSupportedFeatures")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SupportedFeaturesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * Feature list
     * ```
     *
     * `repeated string supported_features = 5;`
     * @param index The index to set the value at.
     * @param value The supportedFeatures to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setSupportedFeatures")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SupportedFeaturesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setSupportedFeatures(index, value)
    }/**
     * ```
     * Feature list
     * ```
     *
     * `repeated string supported_features = 5;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setSupportedFeatures")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, SupportedFeaturesProxy>.clear() {
      _builder.clearSupportedFeatures()
    }
    /**
     * ```
     * For validation
     * ```
     *
     * `string certificate_fingerprint = 6;`
     */
    public var certificateFingerprint: kotlin.String
      @kotlin.jvm.JvmName("getCertificateFingerprint")
        get() = _builder.certificateFingerprint
      @kotlin.jvm.JvmName("setCertificateFingerprint")
        set(value) {
        _builder.certificateFingerprint = value
      }
    /**
     * ```
     * For validation
     * ```
     *
     * `string certificate_fingerprint = 6;`
     */
    public fun clearCertificateFingerprint() {
      _builder.clearCertificateFingerprint()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.System.HelloMessage.copy(block: `droidlink.protocol`.HelloMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.System.HelloMessage =
  `droidlink.protocol`.HelloMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

