// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: media.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializemediaMessage")
public inline fun mediaMessage(block: droidlink.protocol.MediaMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Media.MediaMessage =
  droidlink.protocol.MediaMessageKt.Dsl._create(droidlink.protocol.Media.MediaMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * Virtual webcam and microphone messages
 * ```
 *
 * Protobuf type `droidlink.protocol.MediaMessage`
 */
public object MediaMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.Media.MediaMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.Media.MediaMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.Media.MediaMessage = _builder.build()

    /**
     * `.droidlink.protocol.MediaMessage.MediaEventType event = 1;`
     */
    public var event: droidlink.protocol.Media.MediaMessage.MediaEventType
      @kotlin.jvm.JvmName("getEvent")
        get() = _builder.event
      @kotlin.jvm.JvmName("setEvent")
        set(value) {
        _builder.event = value
      }
    public var eventValue: kotlin.Int
      @kotlin.jvm.JvmName("getEventValue")
        get() = _builder.eventValue
      @kotlin.jvm.JvmName("setEventValue")
        set(value) {
        _builder.eventValue = value
      }
    /**
     * `.droidlink.protocol.MediaMessage.MediaEventType event = 1;`
     */
    public fun clearEvent() {
      _builder.clearEvent()
    }

    /**
     * ```
     * For CAMERA_START
     * ```
     *
     * `.droidlink.protocol.CameraConfig camera_config = 2;`
     */
    public var cameraConfig: droidlink.protocol.Media.CameraConfig
      @kotlin.jvm.JvmName("getCameraConfig")
        get() = _builder.cameraConfig
      @kotlin.jvm.JvmName("setCameraConfig")
        set(value) {
        _builder.cameraConfig = value
      }
    /**
     * ```
     * For CAMERA_START
     * ```
     *
     * `.droidlink.protocol.CameraConfig camera_config = 2;`
     */
    public fun clearCameraConfig() {
      _builder.clearCameraConfig()
    }
    /**
     * ```
     * For CAMERA_START
     * ```
     *
     * `.droidlink.protocol.CameraConfig camera_config = 2;`
     * @return Whether the cameraConfig field is set.
     */
    public fun hasCameraConfig(): kotlin.Boolean {
      return _builder.hasCameraConfig()
    }

    public val MediaMessageKt.Dsl.cameraConfigOrNull: droidlink.protocol.Media.CameraConfig?
      get() = _builder.cameraConfigOrNull

    /**
     * ```
     * For CAMERA_FRAME
     * ```
     *
     * `bytes frame_data = 3;`
     */
    public var frameData: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getFrameData")
        get() = _builder.frameData
      @kotlin.jvm.JvmName("setFrameData")
        set(value) {
        _builder.frameData = value
      }
    /**
     * ```
     * For CAMERA_FRAME
     * ```
     *
     * `bytes frame_data = 3;`
     */
    public fun clearFrameData() {
      _builder.clearFrameData()
    }

    /**
     * `int32 frame_number = 4;`
     */
    public var frameNumber: kotlin.Int
      @kotlin.jvm.JvmName("getFrameNumber")
        get() = _builder.frameNumber
      @kotlin.jvm.JvmName("setFrameNumber")
        set(value) {
        _builder.frameNumber = value
      }
    /**
     * `int32 frame_number = 4;`
     */
    public fun clearFrameNumber() {
      _builder.clearFrameNumber()
    }

    /**
     * `int64 timestamp = 5;`
     */
    public var timestamp: kotlin.Long
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `int64 timestamp = 5;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }

    /**
     * `bool is_keyframe = 6;`
     */
    public var isKeyframe: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsKeyframe")
        get() = _builder.isKeyframe
      @kotlin.jvm.JvmName("setIsKeyframe")
        set(value) {
        _builder.isKeyframe = value
      }
    /**
     * `bool is_keyframe = 6;`
     */
    public fun clearIsKeyframe() {
      _builder.clearIsKeyframe()
    }

    /**
     * ```
     * For MICROPHONE_START
     * ```
     *
     * `.droidlink.protocol.AudioConfig audio_config = 7;`
     */
    public var audioConfig: droidlink.protocol.Media.AudioConfig
      @kotlin.jvm.JvmName("getAudioConfig")
        get() = _builder.audioConfig
      @kotlin.jvm.JvmName("setAudioConfig")
        set(value) {
        _builder.audioConfig = value
      }
    /**
     * ```
     * For MICROPHONE_START
     * ```
     *
     * `.droidlink.protocol.AudioConfig audio_config = 7;`
     */
    public fun clearAudioConfig() {
      _builder.clearAudioConfig()
    }
    /**
     * ```
     * For MICROPHONE_START
     * ```
     *
     * `.droidlink.protocol.AudioConfig audio_config = 7;`
     * @return Whether the audioConfig field is set.
     */
    public fun hasAudioConfig(): kotlin.Boolean {
      return _builder.hasAudioConfig()
    }

    public val MediaMessageKt.Dsl.audioConfigOrNull: droidlink.protocol.Media.AudioConfig?
      get() = _builder.audioConfigOrNull

    /**
     * ```
     * For MICROPHONE_DATA
     * ```
     *
     * `bytes audio_data = 8;`
     */
    public var audioData: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getAudioData")
        get() = _builder.audioData
      @kotlin.jvm.JvmName("setAudioData")
        set(value) {
        _builder.audioData = value
      }
    /**
     * ```
     * For MICROPHONE_DATA
     * ```
     *
     * `bytes audio_data = 8;`
     */
    public fun clearAudioData() {
      _builder.clearAudioData()
    }

    /**
     * `int32 sample_count = 9;`
     */
    public var sampleCount: kotlin.Int
      @kotlin.jvm.JvmName("getSampleCount")
        get() = _builder.sampleCount
      @kotlin.jvm.JvmName("setSampleCount")
        set(value) {
        _builder.sampleCount = value
      }
    /**
     * `int32 sample_count = 9;`
     */
    public fun clearSampleCount() {
      _builder.clearSampleCount()
    }

    /**
     * `int64 audio_timestamp = 10;`
     */
    public var audioTimestamp: kotlin.Long
      @kotlin.jvm.JvmName("getAudioTimestamp")
        get() = _builder.audioTimestamp
      @kotlin.jvm.JvmName("setAudioTimestamp")
        set(value) {
        _builder.audioTimestamp = value
      }
    /**
     * `int64 audio_timestamp = 10;`
     */
    public fun clearAudioTimestamp() {
      _builder.clearAudioTimestamp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.Media.MediaMessage.copy(block: `droidlink.protocol`.MediaMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Media.MediaMessage =
  `droidlink.protocol`.MediaMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val droidlink.protocol.Media.MediaMessageOrBuilder.cameraConfigOrNull: droidlink.protocol.Media.CameraConfig?
  get() = if (hasCameraConfig()) getCameraConfig() else null

public val droidlink.protocol.Media.MediaMessageOrBuilder.audioConfigOrNull: droidlink.protocol.Media.AudioConfig?
  get() = if (hasAudioConfig()) getAudioConfig() else null

