// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notification.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializenotificationData")
public inline fun notificationData(block: droidlink.protocol.NotificationDataKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Notification.NotificationData =
  droidlink.protocol.NotificationDataKt.Dsl._create(droidlink.protocol.Notification.NotificationData.newBuilder()).apply { block() }._build()
/**
 * ```
 * Notification data from Android
 * ```
 *
 * Protobuf type `droidlink.protocol.NotificationData`
 */
public object NotificationDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.Notification.NotificationData.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.Notification.NotificationData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.Notification.NotificationData = _builder.build()

    /**
     * ```
     * Android notification ID
     * ```
     *
     * `string id = 1;`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * ```
     * Android notification ID
     * ```
     *
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * e.g., "com.whatsapp"
     * ```
     *
     * `string package_name = 2;`
     */
    public var packageName: kotlin.String
      @kotlin.jvm.JvmName("getPackageName")
        get() = _builder.packageName
      @kotlin.jvm.JvmName("setPackageName")
        set(value) {
        _builder.packageName = value
      }
    /**
     * ```
     * e.g., "com.whatsapp"
     * ```
     *
     * `string package_name = 2;`
     */
    public fun clearPackageName() {
      _builder.clearPackageName()
    }

    /**
     * ```
     * e.g., "WhatsApp"
     * ```
     *
     * `string app_name = 3;`
     */
    public var appName: kotlin.String
      @kotlin.jvm.JvmName("getAppName")
        get() = _builder.appName
      @kotlin.jvm.JvmName("setAppName")
        set(value) {
        _builder.appName = value
      }
    /**
     * ```
     * e.g., "WhatsApp"
     * ```
     *
     * `string app_name = 3;`
     */
    public fun clearAppName() {
      _builder.clearAppName()
    }

    /**
     * `string title = 4;`
     */
    public var title: kotlin.String
      @kotlin.jvm.JvmName("getTitle")
        get() = _builder.title
      @kotlin.jvm.JvmName("setTitle")
        set(value) {
        _builder.title = value
      }
    /**
     * `string title = 4;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * `string text = 5;`
     */
    public var text: kotlin.String
      @kotlin.jvm.JvmName("getText")
        get() = _builder.text
      @kotlin.jvm.JvmName("setText")
        set(value) {
        _builder.text = value
      }
    /**
     * `string text = 5;`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ActionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .droidlink.protocol.NotificationAction actions = 6;`
     */
     public val actions: com.google.protobuf.kotlin.DslList<droidlink.protocol.Notification.NotificationAction, ActionsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.actionsList
      )
    /**
     * `repeated .droidlink.protocol.NotificationAction actions = 6;`
     * @param value The actions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addActions")
    public fun com.google.protobuf.kotlin.DslList<droidlink.protocol.Notification.NotificationAction, ActionsProxy>.add(value: droidlink.protocol.Notification.NotificationAction) {
      _builder.addActions(value)
    }
    /**
     * `repeated .droidlink.protocol.NotificationAction actions = 6;`
     * @param value The actions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignActions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<droidlink.protocol.Notification.NotificationAction, ActionsProxy>.plusAssign(value: droidlink.protocol.Notification.NotificationAction) {
      add(value)
    }
    /**
     * `repeated .droidlink.protocol.NotificationAction actions = 6;`
     * @param values The actions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllActions")
    public fun com.google.protobuf.kotlin.DslList<droidlink.protocol.Notification.NotificationAction, ActionsProxy>.addAll(values: kotlin.collections.Iterable<droidlink.protocol.Notification.NotificationAction>) {
      _builder.addAllActions(values)
    }
    /**
     * `repeated .droidlink.protocol.NotificationAction actions = 6;`
     * @param values The actions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllActions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<droidlink.protocol.Notification.NotificationAction, ActionsProxy>.plusAssign(values: kotlin.collections.Iterable<droidlink.protocol.Notification.NotificationAction>) {
      addAll(values)
    }
    /**
     * `repeated .droidlink.protocol.NotificationAction actions = 6;`
     * @param index The index to set the value at.
     * @param value The actions to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setActions")
    public operator fun com.google.protobuf.kotlin.DslList<droidlink.protocol.Notification.NotificationAction, ActionsProxy>.set(index: kotlin.Int, value: droidlink.protocol.Notification.NotificationAction) {
      _builder.setActions(index, value)
    }
    /**
     * `repeated .droidlink.protocol.NotificationAction actions = 6;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearActions")
    public fun com.google.protobuf.kotlin.DslList<droidlink.protocol.Notification.NotificationAction, ActionsProxy>.clear() {
      _builder.clearActions()
    }

    /**
     * `int64 timestamp = 7;`
     */
    public var timestamp: kotlin.Long
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `int64 timestamp = 7;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }

    /**
     * ```
     * App icon (PNG, max 100KB)
     * ```
     *
     * `bytes icon = 8;`
     */
    public var icon: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getIcon")
        get() = _builder.icon
      @kotlin.jvm.JvmName("setIcon")
        set(value) {
        _builder.icon = value
      }
    /**
     * ```
     * App icon (PNG, max 100KB)
     * ```
     *
     * `bytes icon = 8;`
     */
    public fun clearIcon() {
      _builder.clearIcon()
    }

    /**
     * ```
     * Can be dismissed
     * ```
     *
     * `bool is_clearable = 9;`
     */
    public var isClearable: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsClearable")
        get() = _builder.isClearable
      @kotlin.jvm.JvmName("setIsClearable")
        set(value) {
        _builder.isClearable = value
      }
    /**
     * ```
     * Can be dismissed
     * ```
     *
     * `bool is_clearable = 9;`
     */
    public fun clearIsClearable() {
      _builder.clearIsClearable()
    }

    /**
     * ```
     * e.g., "msg", "call", "alarm"
     * ```
     *
     * `string category = 10;`
     */
    public var category: kotlin.String
      @kotlin.jvm.JvmName("getCategory")
        get() = _builder.category
      @kotlin.jvm.JvmName("setCategory")
        set(value) {
        _builder.category = value
      }
    /**
     * ```
     * e.g., "msg", "call", "alarm"
     * ```
     *
     * `string category = 10;`
     */
    public fun clearCategory() {
      _builder.clearCategory()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ExtrasProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Additional metadata
     * ```
     *
     * `map<string, string> extras = 11;`
     */
     public val extras: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ExtrasProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getExtrasMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.extrasMap
      )
    /**
     * ```
     * Additional metadata
     * ```
     *
     * `map<string, string> extras = 11;`
     */
    @kotlin.jvm.JvmName("putExtras")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ExtrasProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putExtras(key, value)
       }
    /**
     * ```
     * Additional metadata
     * ```
     *
     * `map<string, string> extras = 11;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setExtras")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ExtrasProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * ```
     * Additional metadata
     * ```
     *
     * `map<string, string> extras = 11;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeExtras")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ExtrasProxy>
      .remove(key: kotlin.String) {
         _builder.removeExtras(key)
       }
    /**
     * ```
     * Additional metadata
     * ```
     *
     * `map<string, string> extras = 11;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllExtras")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ExtrasProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllExtras(map)
       }
    /**
     * ```
     * Additional metadata
     * ```
     *
     * `map<string, string> extras = 11;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearExtras")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ExtrasProxy>
      .clear() {
         _builder.clearExtras()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.Notification.NotificationData.copy(block: `droidlink.protocol`.NotificationDataKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Notification.NotificationData =
  `droidlink.protocol`.NotificationDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

