// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notification.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializenotificationMessage")
public inline fun notificationMessage(block: droidlink.protocol.NotificationMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Notification.NotificationMessage =
  droidlink.protocol.NotificationMessageKt.Dsl._create(droidlink.protocol.Notification.NotificationMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * Notification mirroring messages
 * ```
 *
 * Protobuf type `droidlink.protocol.NotificationMessage`
 */
public object NotificationMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.Notification.NotificationMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.Notification.NotificationMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.Notification.NotificationMessage = _builder.build()

    /**
     * `.droidlink.protocol.NotificationMessage.NotificationEventType event = 1;`
     */
    public var event: droidlink.protocol.Notification.NotificationMessage.NotificationEventType
      @kotlin.jvm.JvmName("getEvent")
        get() = _builder.event
      @kotlin.jvm.JvmName("setEvent")
        set(value) {
        _builder.event = value
      }
    public var eventValue: kotlin.Int
      @kotlin.jvm.JvmName("getEventValue")
        get() = _builder.eventValue
      @kotlin.jvm.JvmName("setEventValue")
        set(value) {
        _builder.eventValue = value
      }
    /**
     * `.droidlink.protocol.NotificationMessage.NotificationEventType event = 1;`
     */
    public fun clearEvent() {
      _builder.clearEvent()
    }

    /**
     * ```
     * For POSTED, UPDATED
     * ```
     *
     * `.droidlink.protocol.NotificationData notification = 2;`
     */
    public var notification: droidlink.protocol.Notification.NotificationData
      @kotlin.jvm.JvmName("getNotification")
        get() = _builder.notification
      @kotlin.jvm.JvmName("setNotification")
        set(value) {
        _builder.notification = value
      }
    /**
     * ```
     * For POSTED, UPDATED
     * ```
     *
     * `.droidlink.protocol.NotificationData notification = 2;`
     */
    public fun clearNotification() {
      _builder.clearNotification()
    }
    /**
     * ```
     * For POSTED, UPDATED
     * ```
     *
     * `.droidlink.protocol.NotificationData notification = 2;`
     * @return Whether the notification field is set.
     */
    public fun hasNotification(): kotlin.Boolean {
      return _builder.hasNotification()
    }

    public val NotificationMessageKt.Dsl.notificationOrNull: droidlink.protocol.Notification.NotificationData?
      get() = _builder.notificationOrNull

    /**
     * ```
     * For REMOVED
     * ```
     *
     * `string notification_id = 3;`
     */
    public var notificationId: kotlin.String
      @kotlin.jvm.JvmName("getNotificationId")
        get() = _builder.notificationId
      @kotlin.jvm.JvmName("setNotificationId")
        set(value) {
        _builder.notificationId = value
      }
    /**
     * ```
     * For REMOVED
     * ```
     *
     * `string notification_id = 3;`
     */
    public fun clearNotificationId() {
      _builder.clearNotificationId()
    }

    /**
     * ```
     * For ACTION_CLICKED
     * ```
     *
     * `string action_id = 4;`
     */
    public var actionId: kotlin.String
      @kotlin.jvm.JvmName("getActionId")
        get() = _builder.actionId
      @kotlin.jvm.JvmName("setActionId")
        set(value) {
        _builder.actionId = value
      }
    /**
     * ```
     * For ACTION_CLICKED
     * ```
     *
     * `string action_id = 4;`
     */
    public fun clearActionId() {
      _builder.clearActionId()
    }

    /**
     * ```
     * For reply actions
     * ```
     *
     * `string action_reply_text = 5;`
     */
    public var actionReplyText: kotlin.String
      @kotlin.jvm.JvmName("getActionReplyText")
        get() = _builder.actionReplyText
      @kotlin.jvm.JvmName("setActionReplyText")
        set(value) {
        _builder.actionReplyText = value
      }
    /**
     * ```
     * For reply actions
     * ```
     *
     * `string action_reply_text = 5;`
     */
    public fun clearActionReplyText() {
      _builder.clearActionReplyText()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.Notification.NotificationMessage.copy(block: `droidlink.protocol`.NotificationMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Notification.NotificationMessage =
  `droidlink.protocol`.NotificationMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val droidlink.protocol.Notification.NotificationMessageOrBuilder.notificationOrNull: droidlink.protocol.Notification.NotificationData?
  get() = if (hasNotification()) getNotification() else null

