// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notification.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializenotificationAction")
public inline fun notificationAction(block: droidlink.protocol.NotificationActionKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Notification.NotificationAction =
  droidlink.protocol.NotificationActionKt.Dsl._create(droidlink.protocol.Notification.NotificationAction.newBuilder()).apply { block() }._build()
/**
 * ```
 * Notification action button
 * ```
 *
 * Protobuf type `droidlink.protocol.NotificationAction`
 */
public object NotificationActionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.Notification.NotificationAction.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.Notification.NotificationAction.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.Notification.NotificationAction = _builder.build()

    /**
     * `string id = 1;`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * e.g., "Reply", "Dismiss"
     * ```
     *
     * `string label = 2;`
     */
    public var label: kotlin.String
      @kotlin.jvm.JvmName("getLabel")
        get() = _builder.label
      @kotlin.jvm.JvmName("setLabel")
        set(value) {
        _builder.label = value
      }
    /**
     * ```
     * e.g., "Reply", "Dismiss"
     * ```
     *
     * `string label = 2;`
     */
    public fun clearLabel() {
      _builder.clearLabel()
    }

    /**
     * `.droidlink.protocol.ActionType type = 3;`
     */
    public var type: droidlink.protocol.Notification.ActionType
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    public var typeValue: kotlin.Int
      @kotlin.jvm.JvmName("getTypeValue")
        get() = _builder.typeValue
      @kotlin.jvm.JvmName("setTypeValue")
        set(value) {
        _builder.typeValue = value
      }
    /**
     * `.droidlink.protocol.ActionType type = 3;`
     */
    public fun clearType() {
      _builder.clearType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.Notification.NotificationAction.copy(block: `droidlink.protocol`.NotificationActionKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Notification.NotificationAction =
  `droidlink.protocol`.NotificationActionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

