// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: screen.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializescreenMessage")
public inline fun screenMessage(block: droidlink.protocol.ScreenMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Screen.ScreenMessage =
  droidlink.protocol.ScreenMessageKt.Dsl._create(droidlink.protocol.Screen.ScreenMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * Screen mirroring messages
 * ```
 *
 * Protobuf type `droidlink.protocol.ScreenMessage`
 */
public object ScreenMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.Screen.ScreenMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.Screen.ScreenMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.Screen.ScreenMessage = _builder.build()

    /**
     * `.droidlink.protocol.ScreenMessage.StreamEventType event = 1;`
     */
    public var event: droidlink.protocol.Screen.ScreenMessage.StreamEventType
      @kotlin.jvm.JvmName("getEvent")
        get() = _builder.event
      @kotlin.jvm.JvmName("setEvent")
        set(value) {
        _builder.event = value
      }
    public var eventValue: kotlin.Int
      @kotlin.jvm.JvmName("getEventValue")
        get() = _builder.eventValue
      @kotlin.jvm.JvmName("setEventValue")
        set(value) {
        _builder.eventValue = value
      }
    /**
     * `.droidlink.protocol.ScreenMessage.StreamEventType event = 1;`
     */
    public fun clearEvent() {
      _builder.clearEvent()
    }

    /**
     * ```
     * For START
     * ```
     *
     * `.droidlink.protocol.StreamConfig config = 2;`
     */
    public var config: droidlink.protocol.Screen.StreamConfig
      @kotlin.jvm.JvmName("getConfig")
        get() = _builder.config
      @kotlin.jvm.JvmName("setConfig")
        set(value) {
        _builder.config = value
      }
    /**
     * ```
     * For START
     * ```
     *
     * `.droidlink.protocol.StreamConfig config = 2;`
     */
    public fun clearConfig() {
      _builder.clearConfig()
    }
    /**
     * ```
     * For START
     * ```
     *
     * `.droidlink.protocol.StreamConfig config = 2;`
     * @return Whether the config field is set.
     */
    public fun hasConfig(): kotlin.Boolean {
      return _builder.hasConfig()
    }

    public val ScreenMessageKt.Dsl.configOrNull: droidlink.protocol.Screen.StreamConfig?
      get() = _builder.configOrNull

    /**
     * ```
     * For FRAME
     * ```
     *
     * `bytes frame_data = 3;`
     */
    public var frameData: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getFrameData")
        get() = _builder.frameData
      @kotlin.jvm.JvmName("setFrameData")
        set(value) {
        _builder.frameData = value
      }
    /**
     * ```
     * For FRAME
     * ```
     *
     * `bytes frame_data = 3;`
     */
    public fun clearFrameData() {
      _builder.clearFrameData()
    }

    /**
     * `int32 frame_number = 4;`
     */
    public var frameNumber: kotlin.Int
      @kotlin.jvm.JvmName("getFrameNumber")
        get() = _builder.frameNumber
      @kotlin.jvm.JvmName("setFrameNumber")
        set(value) {
        _builder.frameNumber = value
      }
    /**
     * `int32 frame_number = 4;`
     */
    public fun clearFrameNumber() {
      _builder.clearFrameNumber()
    }

    /**
     * `int64 timestamp = 5;`
     */
    public var timestamp: kotlin.Long
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `int64 timestamp = 5;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }

    /**
     * ```
     * Sync frame
     * ```
     *
     * `bool is_keyframe = 6;`
     */
    public var isKeyframe: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsKeyframe")
        get() = _builder.isKeyframe
      @kotlin.jvm.JvmName("setIsKeyframe")
        set(value) {
        _builder.isKeyframe = value
      }
    /**
     * ```
     * Sync frame
     * ```
     *
     * `bool is_keyframe = 6;`
     */
    public fun clearIsKeyframe() {
      _builder.clearIsKeyframe()
    }

    /**
     * ```
     * For ERROR
     * ```
     *
     * `string error_message = 7;`
     */
    public var errorMessage: kotlin.String
      @kotlin.jvm.JvmName("getErrorMessage")
        get() = _builder.errorMessage
      @kotlin.jvm.JvmName("setErrorMessage")
        set(value) {
        _builder.errorMessage = value
      }
    /**
     * ```
     * For ERROR
     * ```
     *
     * `string error_message = 7;`
     */
    public fun clearErrorMessage() {
      _builder.clearErrorMessage()
    }

    /**
     * ```
     * For PAUSE/RESUME
     * ```
     *
     * `int64 paused_at = 8;`
     */
    public var pausedAt: kotlin.Long
      @kotlin.jvm.JvmName("getPausedAt")
        get() = _builder.pausedAt
      @kotlin.jvm.JvmName("setPausedAt")
        set(value) {
        _builder.pausedAt = value
      }
    /**
     * ```
     * For PAUSE/RESUME
     * ```
     *
     * `int64 paused_at = 8;`
     */
    public fun clearPausedAt() {
      _builder.clearPausedAt()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.Screen.ScreenMessage.copy(block: `droidlink.protocol`.ScreenMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Screen.ScreenMessage =
  `droidlink.protocol`.ScreenMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val droidlink.protocol.Screen.ScreenMessageOrBuilder.configOrNull: droidlink.protocol.Screen.StreamConfig?
  get() = if (hasConfig()) getConfig() else null

