// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: screen.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializestreamConfig")
public inline fun streamConfig(block: droidlink.protocol.StreamConfigKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Screen.StreamConfig =
  droidlink.protocol.StreamConfigKt.Dsl._create(droidlink.protocol.Screen.StreamConfig.newBuilder()).apply { block() }._build()
/**
 * ```
 * Stream configuration
 * ```
 *
 * Protobuf type `droidlink.protocol.StreamConfig`
 */
public object StreamConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.Screen.StreamConfig.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.Screen.StreamConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.Screen.StreamConfig = _builder.build()

    /**
     * ```
     * Video width
     * ```
     *
     * `int32 width = 1;`
     */
    public var width: kotlin.Int
      @kotlin.jvm.JvmName("getWidth")
        get() = _builder.width
      @kotlin.jvm.JvmName("setWidth")
        set(value) {
        _builder.width = value
      }
    /**
     * ```
     * Video width
     * ```
     *
     * `int32 width = 1;`
     */
    public fun clearWidth() {
      _builder.clearWidth()
    }

    /**
     * ```
     * Video height
     * ```
     *
     * `int32 height = 2;`
     */
    public var height: kotlin.Int
      @kotlin.jvm.JvmName("getHeight")
        get() = _builder.height
      @kotlin.jvm.JvmName("setHeight")
        set(value) {
        _builder.height = value
      }
    /**
     * ```
     * Video height
     * ```
     *
     * `int32 height = 2;`
     */
    public fun clearHeight() {
      _builder.clearHeight()
    }

    /**
     * ```
     * Target FPS
     * ```
     *
     * `int32 fps = 3;`
     */
    public var fps: kotlin.Int
      @kotlin.jvm.JvmName("getFps")
        get() = _builder.fps
      @kotlin.jvm.JvmName("setFps")
        set(value) {
        _builder.fps = value
      }
    /**
     * ```
     * Target FPS
     * ```
     *
     * `int32 fps = 3;`
     */
    public fun clearFps() {
      _builder.clearFps()
    }

    /**
     * ```
     * Bitrate (kbps)
     * ```
     *
     * `int32 bitrate = 4;`
     */
    public var bitrate: kotlin.Int
      @kotlin.jvm.JvmName("getBitrate")
        get() = _builder.bitrate
      @kotlin.jvm.JvmName("setBitrate")
        set(value) {
        _builder.bitrate = value
      }
    /**
     * ```
     * Bitrate (kbps)
     * ```
     *
     * `int32 bitrate = 4;`
     */
    public fun clearBitrate() {
      _builder.clearBitrate()
    }

    /**
     * `.droidlink.protocol.VideoCodec codec = 5;`
     */
    public var codec: droidlink.protocol.Screen.VideoCodec
      @kotlin.jvm.JvmName("getCodec")
        get() = _builder.codec
      @kotlin.jvm.JvmName("setCodec")
        set(value) {
        _builder.codec = value
      }
    public var codecValue: kotlin.Int
      @kotlin.jvm.JvmName("getCodecValue")
        get() = _builder.codecValue
      @kotlin.jvm.JvmName("setCodecValue")
        set(value) {
        _builder.codecValue = value
      }
    /**
     * `.droidlink.protocol.VideoCodec codec = 5;`
     */
    public fun clearCodec() {
      _builder.clearCodec()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.Screen.StreamConfig.copy(block: `droidlink.protocol`.StreamConfigKt.Dsl.() -> kotlin.Unit): droidlink.protocol.Screen.StreamConfig =
  `droidlink.protocol`.StreamConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

