// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: system.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package droidlink.protocol;

@kotlin.jvm.JvmName("-initializesystemMessage")
public inline fun systemMessage(block: droidlink.protocol.SystemMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.System.SystemMessage =
  droidlink.protocol.SystemMessageKt.Dsl._create(droidlink.protocol.System.SystemMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * Connection lifecycle and system control messages
 * ```
 *
 * Protobuf type `droidlink.protocol.SystemMessage`
 */
public object SystemMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: droidlink.protocol.System.SystemMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: droidlink.protocol.System.SystemMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): droidlink.protocol.System.SystemMessage = _builder.build()

    /**
     * `.droidlink.protocol.SystemMessage.SystemEventType event = 1;`
     */
    public var event: droidlink.protocol.System.SystemMessage.SystemEventType
      @kotlin.jvm.JvmName("getEvent")
        get() = _builder.event
      @kotlin.jvm.JvmName("setEvent")
        set(value) {
        _builder.event = value
      }
    public var eventValue: kotlin.Int
      @kotlin.jvm.JvmName("getEventValue")
        get() = _builder.eventValue
      @kotlin.jvm.JvmName("setEventValue")
        set(value) {
        _builder.eventValue = value
      }
    /**
     * `.droidlink.protocol.SystemMessage.SystemEventType event = 1;`
     */
    public fun clearEvent() {
      _builder.clearEvent()
    }

    /**
     * ```
     * For HELLO
     * ```
     *
     * `.droidlink.protocol.HelloMessage hello = 10;`
     */
    public var hello: droidlink.protocol.System.HelloMessage
      @kotlin.jvm.JvmName("getHello")
        get() = _builder.hello
      @kotlin.jvm.JvmName("setHello")
        set(value) {
        _builder.hello = value
      }
    /**
     * ```
     * For HELLO
     * ```
     *
     * `.droidlink.protocol.HelloMessage hello = 10;`
     */
    public fun clearHello() {
      _builder.clearHello()
    }
    /**
     * ```
     * For HELLO
     * ```
     *
     * `.droidlink.protocol.HelloMessage hello = 10;`
     * @return Whether the hello field is set.
     */
    public fun hasHello(): kotlin.Boolean {
      return _builder.hasHello()
    }

    public val SystemMessageKt.Dsl.helloOrNull: droidlink.protocol.System.HelloMessage?
      get() = _builder.helloOrNull

    /**
     * ```
     * For HELLO_ACK
     * ```
     *
     * `.droidlink.protocol.HelloAckMessage hello_ack = 11;`
     */
    public var helloAck: droidlink.protocol.System.HelloAckMessage
      @kotlin.jvm.JvmName("getHelloAck")
        get() = _builder.helloAck
      @kotlin.jvm.JvmName("setHelloAck")
        set(value) {
        _builder.helloAck = value
      }
    /**
     * ```
     * For HELLO_ACK
     * ```
     *
     * `.droidlink.protocol.HelloAckMessage hello_ack = 11;`
     */
    public fun clearHelloAck() {
      _builder.clearHelloAck()
    }
    /**
     * ```
     * For HELLO_ACK
     * ```
     *
     * `.droidlink.protocol.HelloAckMessage hello_ack = 11;`
     * @return Whether the helloAck field is set.
     */
    public fun hasHelloAck(): kotlin.Boolean {
      return _builder.hasHelloAck()
    }

    public val SystemMessageKt.Dsl.helloAckOrNull: droidlink.protocol.System.HelloAckMessage?
      get() = _builder.helloAckOrNull

    /**
     * ```
     * For ERROR
     * ```
     *
     * `.droidlink.protocol.ErrorMessage error = 12;`
     */
    public var error: droidlink.protocol.System.ErrorMessage
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * ```
     * For ERROR
     * ```
     *
     * `.droidlink.protocol.ErrorMessage error = 12;`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * ```
     * For ERROR
     * ```
     *
     * `.droidlink.protocol.ErrorMessage error = 12;`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val SystemMessageKt.Dsl.errorOrNull: droidlink.protocol.System.ErrorMessage?
      get() = _builder.errorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun droidlink.protocol.System.SystemMessage.copy(block: `droidlink.protocol`.SystemMessageKt.Dsl.() -> kotlin.Unit): droidlink.protocol.System.SystemMessage =
  `droidlink.protocol`.SystemMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val droidlink.protocol.System.SystemMessageOrBuilder.helloOrNull: droidlink.protocol.System.HelloMessage?
  get() = if (hasHello()) getHello() else null

public val droidlink.protocol.System.SystemMessageOrBuilder.helloAckOrNull: droidlink.protocol.System.HelloAckMessage?
  get() = if (hasHelloAck()) getHelloAck() else null

public val droidlink.protocol.System.SystemMessageOrBuilder.errorOrNull: droidlink.protocol.System.ErrorMessage?
  get() = if (hasError()) getError() else null

